

services:
  postgres:
    image: postgres:15
    container_name: liquibase
    restart: always
    environment:

      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

  redis:
    image: redis:latest
    container_name: redis_liquibase
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  my-network:
