server:
  port: 8090

spring:
  profiles:
    active: dev
  liquibase:
    enabled: true
    #default-schema: ${db.schema}
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    database: POSTGRESQL
    show-sql: true
    database-platform : org.hibernate.dialect.PostgreSQLDialect

    properties:
      hibernate:
        ddl-auto: none

  datasource:
    url: jdbc:postgresql://localhost:5432/product-database
    username: admin
    password: admin

  data:
    redis:
      host: localhost
      port: 6379




  main:
    allow-bean-definition-overriding: true
